[package]
name = "hello-world"
version = "0.1.0"
authors = ["Núria Balaguer <nyxscream@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "0.7"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
